Web/Controllers/ErrorController.cs
using System.Web.Mvc;

namespace Web.Controllers
{
    public class ErrorController : Controller
    {
       
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NotFound()
        {
            return View();
        }

        public ActionResult AccessDenied()
        {
            return View();
        }
    }
}

Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Infrastructure;

namespace Web.Controllers
{
    public class LoginController : BaseController
    {
        //
        // GET: /Login/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Web/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Infrastructure;
using Infrastructure.Extentions;
using Telerik.Web.Mvc;

namespace Web.Controllers
{
    public class TestController : BaseController
    {
       


        public ActionResult Index()
        {

            base.UserManager = new UserManager
                                   {
                                       Id = 1,
                                       Name = "testUser",
                                       IsAuthenticated = true
                                   };
            return View();

        }


        public ActionResult Error()
        {
            this.ShowMessage(MessageType.Error, "Error");
            return View("Index");
        }

        public ActionResult Success()
        {
            this.ShowMessage(MessageType.Success, "Success");
            return View("Index");
        }

        public ActionResult Warning()
        {
            this.ShowMessage(MessageType.Warning, "Warning");
            return View("Index");
        }



        public ActionResult RedirectError()
        {
            this.ShowMessage(MessageType.Error, "RedirectError", true);
            return View();
        }

        public ActionResult RedirectSuccess()
        {
            this.ShowMessage(MessageType.Success, "RedirectSuccess", true);
            return View();
        }

        public ActionResult RedirectWarning()
        {
            this.ShowMessage(MessageType.Warning, "RedirectWarning", true);
            return View();
        }


        [HttpPost]
        public ActionResult ErrorAjax()
        {
            this.ShowMessage(MessageType.Error, "Error");
            return new JsonResult
            {
                Data = new { Success = true }
            };
        }

        public ActionResult SuccessAjax()
        {
            this.ShowMessage(MessageType.Success, "Success");
            return new JsonResult
            {
                Data = new { Success = true }
            };
        }

        public ActionResult WarningAjax()
        {
            this.ShowMessage(MessageType.Warning, "Warning");
            return new JsonResult
            {
                Data = new { Success = true }
            };
        }



        public ActionResult UnAuthorizedException()
        {
            throw new UnauthorizedAccessException("UnauthorizedAccessException");

        }

        [HttpPost]
        public JsonResult AjaxUnAuthorizedException()
        {
            throw new UnauthorizedAccessException("UnauthorizedAccessException");
        }



        public ActionResult UnHandledException()
        {
            throw new HttpUnhandledException("HttpUnhandledException");
        }

        [HttpPost]
        public JsonResult AjaxUnHandledException()
        {
            throw new HttpUnhandledException("HttpUnhandledException");
        }



        [GridAction(EnableCustomBinding = true)]
        public ActionResult LoadGrid(GridCommand command, int? id, string text, int? errorTypeId)
        {
            switch (errorTypeId)
            {
                case 0:
                    throw new HttpUnhandledException("HttpUnhandledException");
                case 1:
                    throw new UnauthorizedAccessException("UnauthorizedAccessException");
                case 2:
                    this.ShowMessage(MessageType.Warning, "Warning");
                    return new JsonResult { Data = new GridModel<User> { Data = null, Total = 0 } };
                case 3:
                    this.ShowMessage(MessageType.Success, "Success");
                    return new JsonResult { Data = new GridModel<User> { Data = null, Total = 0 } };
                case 4:
                    this.ShowMessage(MessageType.Error, "Error");
                    return new JsonResult { Data = new GridModel<User> { Data = null, Total = 0 } };
            }
            var list = new List<User>
            {
                new User {Id = 0, Name = "Noname1"},
                new User {Id = 1, Name = "Noname2"},
                new User {Id = 2, Name = "Noname3"},
                new User {Id = 3, Name = "Noname4"}
            };
            list = list.Where(u => u.Name.Contains(text) || u.Id == id).ToList();
            return new JsonResult
            {
                Data = new GridModel<User> { Data = list, Total = list.Count }
            };
        }

    }

    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ErrorTypeId { get; set; }

    }
}

Web/Views/Login/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";


}

<h2>Login</h2>
Login Page

<br/>


  @Html.ActionLink("Redirect To Test Page", "Index", "Test")

Web/Views/Shared/_Layout.cshtml
@using Infrastructure.Extentions
@using Telerik.Web.Mvc.UI
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @(Html.Telerik().
    StyleSheetRegistrar().
    DefaultGroup(group => group.Add("telerik.common.css").
    Add("telerik.default.css").
    Combined(true).
    Compress(true)))
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>

    <script type="text/javascript">

        $(document).ready(function () {
            handleAjaxMessages();
            displayMessages();
        });

        function displayMessage(message, messageType) {
            $("#messagewrapper").html('<div class="messagebox ' + messageType.toLowerCase() + '"></div>');
            $("#messagewrapper .messagebox").text(message);
            displayMessages();
        }

        function displayMessages() {
            if ($("#messagewrapper").children().length > 0) {
                $("#messagewrapper").show();
                $(document).click(function () {
                    clearMessages();
                });
            }
            else {
                $("#messagewrapper").hide();
            }
        }

        function clearMessages() {
            $("#messagewrapper").fadeOut(500, function () {
                $("#messagewrapper").empty();
            });
        }

        function handleAjaxMessages() {
            $(document).ajaxStart(function () {
                $('#ajax-busy').addClass("busy");
            }).ajaxError(function (event, request) {
                window.setTimeout(function () {
                    $('#ajax-busy').removeClass("busy");
                }, 300);
                if (request.status == 403)  //Authorization error
                {
                    var url = request.getResponseHeader('X-RedirectUrl');
                    alert("Session time out...");
                    $(location).attr('href', url);

                } else {
                    displayMessage(request.responseText, "error");

                }

            }).ajaxSuccess(function (event, request) {
                checkAndHandleMessageFromHeader(request);
            }).ajaxComplete(function (event, request, opts) {
                window.setTimeout(function () {
                    $('#ajax-busy').removeClass("busy");
                }, 300);
            }).ajaxStop(function () {
                window.setTimeout(function () {
                    $('#ajax-busy').removeClass("busy");
                }, 300);
            });
        }

        function checkAndHandleMessageFromHeader(request) {
            var msg = request.getResponseHeader('X-Message');
            if (msg) {
                displayMessage(msg, request.getResponseHeader('X-Message-Type'));
            }
        }

    </script>
</head>
<body>
    <header>
            <div id="ajax-busy"></div>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    @*  @Html.ActionLink("your logo here", "Index", "Home")*@
                </p>
            </div>
            <div class="float-right">
                <section id="login">
                    @*    @Html.Partial("_LoginPartial")*@
                </section>
                <nav>
                    <ul id="menu">
                        @*  <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            <div id="messagewrapper" style="display: none">
                @Html.RenderMessages()
            </div>
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
    @(Html.Telerik()
    .ScriptRegistrar().
        DefaultGroup(group => group.Combined(false).CacheDurationInDays(5).
        Add("telerik.all.min.js").
        Add("telerik.common.min.js").
        Compress(true)).CombinedComponentFile(true).
        jQuery(false).
        jQueryValidation(false).
        Globalization(true))
</body>
</html>

<style type="text/css">
    
    /* Notification styles
-----------------------------------------------------------*/
#messagewrapper
{
	position: fixed;
	top: 0px;
	right: 10px;
	z-index: 1000;
	margin: 5px auto;
	width: 500px;
}

#messagewrapper .messagebox
{
	padding: 12px 10px 10px 30px;
	box-shadow: 5px 5px 10px #000;
}

#messagewrapper .success
{
	color: #060;
	background: #cfc url(../../images/ok.gif) no-repeat 8px 12px;
}

#messagewrapper .warning
{
	color: #c60;
	background: #ffc url(../../images/warn.gif) no-repeat 8px 12px;
}

#messagewrapper .error
{
	color: #c00;
	background: #fcc url(../../images/fail.gif) no-repeat 8px 12px;
}

.t-combobox .t-input
{
    border-top-width: 1px;
    border-bottom-width: 1px;
}
#ajax-busy {
    position: absolute;
    width: 64px;
    height: 64px;
    padding: 0;
    background: transparent url('../../images/loader.gif') 50% 50% no-repeat;
    margin: 0 50% auto;
    top: 0;
    visibility: hidden;
    margin-top: -5px;
    .opacity(0);
    .transition(opacity 0.15s linear);
}
#ajax-busy.busy {
    visibility: visible;
    .opacity(100);
}
</style>

Web/Views/Test/Index.cshtml
@using Infrastructure.Extentions

@using Telerik.Web.Mvc.UI
@using Web.Controllers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Web.Controllers.User

@{
   

}

<h2>Get Method Notification Types</h2>
<a href="/Test/Error" class="t-button">Error</a>
<a href="/Test/Warning" class="t-button">Warning</a>
<a href="/Test/Success" class="t-button">Success</a>

<h2>Get Method Redirect Notification Types</h2>
<a href="/Test/RedirectError" class="t-button">Redirect Error</a>
<a href="/Test/RedirectWarning" class="t-button">Redirect Warning</a>
<a href="/Test/RedirectSuccess" class="t-button">Redirect Success</a>

<br />
<h2>Ajax Call  Notification Types</h2>
<button id="Errorajax" class="t-button" onclick="Errorajax();">Ajax Error</button>
<button id="Warningajax" class="t-button" onclick="Warningajax();">Ajax Warning</button>
<button id="Successajax" class="t-button" onclick="Successajax();">
    Ajax Success
</button>
<h2>Unhandled  Exception Types</h2>
<a href="/Test/UnhandledException" class="t-button">Unhandled Exception</a>
<button id="ajaxunhandled" class="t-button" onclick="Ajaxunhandled();">
    Ajax  Unhandled
    Exception</button>

<h2>UnauthorizedAccessException   Types</h2>
<a href="/Test/UnAuthorizedException" class="t-button">UnauthorizedAccessException
</a>
<button id="AjaxUnauthorizedAccessException" class="t-button" onclick="AjaxUnauthorizedAccessException();">
    Ajax  UnauthorizedAccessException</button>

<br />
<h2>Telerik Grid   </h2>
<br />
<h2>Grid Error Type:</h2>
<br />
@(Html.Telerik().DropDownList()
                          .Name("ErrorTypeId")
                          .HtmlAttributes(new { style = "width: 300px;" })
                          .DropDownHtmlAttributes(new { style = "height: 300px" })
                          .BindTo(new List<SelectListItem>()
                                      { 
                                        new SelectListItem(){Selected = false,Text = "-Select-",Value = "-1"},
                                          new SelectListItem(){Selected = false,Text = "HttpUnhandledException",Value = "0"},
                                             new SelectListItem(){Selected = false,Text = "UnauthorizedAccessException",Value = "1"},
                                                new SelectListItem(){Selected = false,Text = "Warning",Value = "2"},
                                                   new SelectListItem(){Selected = false,Text = "Success",Value = "3"},
                                                      new SelectListItem(){Selected = false,Text = "Error",Value = "4"}
                                      })
       )
<br />
<h2>Search:</h2>
<br />
@Html.LabelFor(i => i.Id)
@Html.EditorFor(i => i.Id)
@Html.LabelFor(i => i.Name)
@Html.EditorFor(i => i.Name)
@(Html.Telerik().Grid<User>()
              .Name("grd_test")
              .Columns(columns =>
              {
                  columns.Bound(q => q.Id);
                  columns.Bound(q => q.Name);
              })
              .Pageable(settings => settings.Position(GridPagerPosition.Both).PageSize(20))
              .DataBinding(dataBinding => dataBinding.Ajax().Select("LoadGrid", "Test"))
              .ClientEvents(events => events.OnDataBinding("onDataBinding").OnError("onError"))
      .EnableCustomBinding(true))
<br />
<button id="testGridSearch" class="t-button">Search </button>
<script type="text/javascript">

    function searchbind() {
        var grid = $('#grd_test').data('tGrid');
        grid.currentPage = 1; //new search. Set page size to 1
        grid.ajaxRequest();
        return false;
    }

    function onDataBinding(e) {

        var searchModel = {
            id: $('#Id').val(),
            text: $('#Name').val(),
            errorTypeId: $('#ErrorTypeId').val()
        };
        e.data = searchModel;

    }

    function refreshGrid() {
        var grid = $('#grd_test').data('tGrid');
        grid.ajaxRequest();
        return false;
    }

    function onError(e) {
        if (e.textStatus == 'error') {
            if (e.XMLHttpRequest.status == "500" || e.XMLHttpRequest.status == "403") {
                e.preventDefault();
            }
        }
    }

    $(document).ready(function () {
        $('#testGridSearch').click(function () {
            var grid = $('#grd_test').data('tGrid');
            grid.currentPage = 1; //new search. Set page size to 1
            grid.ajaxRequest();
            return false;
        });

    });

</script>
<script type="text/javascript">


    function Errorajax() {

        Type = "POST";
        Url = '@Url.Action("ErrorAjax", "Test")';
        ContentType = "application/json; charset=utf-8";
        DataType = "json";
        CallAction();
    }

    function Warningajax() {

        Type = "POST";
        Url = '@Url.Action("WarningAjax", "Test")';
        ContentType = "application/json; charset=utf-8";
        DataType = "json";
        CallAction();
    }

    function Successajax() {

        Type = "POST";
        Url = '@Url.Action("SuccessAjax", "Test")';
        ContentType = "application/json; charset=utf-8";
        DataType = "json";
        CallAction();
    }

    function Ajaxunhandled() {

        Type = "POST";
        Url = '@Url.Action("AjaxUnHandledException", "Test")';
        ContentType = "application/json; charset=utf-8";
        DataType = "json";
        CallAction();
    }

    function AjaxUnauthorizedAccessException() {

        Type = "POST";
        Url = '@Url.Action("AjaxUnAuthorizedException", "Test")';
        ContentType = "application/json; charset=utf-8";
        DataType = "json";
        CallAction();
    }

    var Type;
    var Url;
    var Data;
    var ContentType;
    var DataType;
    var ProcessData;
    function CallAction() {
        $.ajax({
            type: Type, //GET,POST,PUT or DELETE verb
            url: Url, // Location of the action
            data: Data, //Data to be sent to server
            contentType: ContentType, // content type sent to action
            dataType: DataType, //Expected data format from action
            success: function (msg) {  //On Successful service call
                ActionSucceeded(msg);
            },
            error: ActionFailed // function When Service call fails
        });
    }

    function ActionFailed(result) {
        //alert('Service call failed: ' + result.status + '' + result.statusText);
        Type = null; Url = null; Data = null; ContentType = null; DataType = null; ProcessData = null;
    }

    function ActionSucceeded(result) {
    }

    function ActionFailed(xhr) {
        return;
    }



</script>

Web/Views/Test/RedirectError.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Error</h2>

Web/Views/Test/RedirectSuccess.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Success</h2>

Web/Views/Test/RedirectWarning.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Warning</h2>

Web/Views/Test/Warning.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Warnig</h2>